### ISSUE TITLE
error when inserting osu! stream version into db

### ISSUE THREAD

**Issue by cmyui** [osuAkatsuki/bancho.py#188]
reported by `-lokillo-#9990` in discord
```sh
lokillo@DESKTOP-KKAONBB:~/bancho.py$ ./main.py
[06:24:42AM] Fetching channels from sql.
[06:24:42AM] Fetching clans from sql.
[06:24:42AM] Fetching mappools from sql.
[06:24:42AM] Initializing housekeeping tasks.
[06:24:42AM] Startup process complete.
[06:24:42AM] Listening @ /tmp/bancho.sock
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/lokillo/.local/lib/python3.9/site-packages/anyio/streams/memory.py", line 81, in receive
    return self.receive_nowait()
  File "/home/lokillo/.local/lib/python3.9/site-packages/anyio/streams/memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "/home/lokillo/.local/lib/python3.9/site-packages/anyio/streams/memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/lokillo/.local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/lokillo/bancho.py/app/api/init_api.py", line 61, in http_middleware
    return await call_next(request)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/home/lokillo/bancho.py/app/api/middlewares.py", line 22, in dispatch
    response = await call_next(request)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/routing.py", line 472, in handle
    await self.app(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/lokillo/.local/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/lokillo/.local/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/lokillo/.local/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/lokillo/bancho.py/app/api/domains/cho.py", line 115, in bancho_handler
    login_data = await login(await request.body(), ip, db_conn)
  File "/home/lokillo/bancho.py/app/api/domains/cho.py", line 606, in login
    await db_conn.execute(
  File "/home/lokillo/.local/lib/python3.9/site-packages/databases/core.py", line 295, in execute
    return await self._connection.execute(built_query)
  File "/home/lokillo/.local/lib/python3.9/site-packages/databases/backends/mysql.py", line 149, in execute
    await cursor.execute(query_str, args)
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/connection.py", line 620, in _read_query_result
    await result.read()
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/connection.py", line 1103, in read
    first_packet = await self.connection._read_packet()
  File "/home/lokillo/.local/lib/python3.9/site-packages/aiomysql/connection.py", line 591, in _read_packet
    packet.check_error()
  File "/home/lokillo/.local/lib/python3.9/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/lokillo/.local/lib/python3.9/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1048, "Column 'osu_stream' cannot be null")
[06:24:55AM] [GET] 401 osu.ppy.sh/web/bancho_connect.php | Request took: 730.50 μsec```

**Comment by cmyui** [comment]
closed with 2f972bbbe11ea9076d2eed9b527f300aec833def
