### ISSUE TITLE
mixed use of unsigned int and int cause user not be able to login

### ISSUE THREAD

**Issue by arily** [osuAkatsuki/bancho.py#305]
Our private server got a report that one of our users cannot login.
After investigating, we found out that this behavior is caused by an exception in creating an osu client packet.

Here is the database structure:
https://github.com/osuAkatsuki/bancho.py/blob/7c6b541b906574deb69f12af9168d534c7adc97f/migrations/base.sql#L91

and here is the sterilization of the "user friends list" (which caused the exception)
https://github.com/osuAkatsuki/bancho.py/blob/3dc5b4dc3a22d0e27396631fbefe642886815c69/app/packets.py#L1069

For unknown reasons, this user has a friend with an id of -1 and this exception is not been handled thus the whole login failed.

here's the backtrace of the exception
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/anyio/streams/memory.py", line 81, in receive
    return self.receive_nowait()
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/anyio/streams/memory.py", line 76, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 41, in call_next
    message = await recv_stream.receive()
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/anyio/streams/memory.py", line 101, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/osu-server/bancho.py/app/api/init_api.py", line 111, in http_middleware
    return await call_next(request)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 63, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/osu-server/bancho.py/app/api/middlewares.py", line 23, in dispatch
    response = await call_next(request)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 44, in call_next
    raise app_exc
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/middleware/base.py", line 34, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/routing.py", line 472, in handle
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/root/.pyenv/versions/3.9.6/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/osu-server/bancho.py/app/api/domains/cho.py", line 112, in bancho_handler
    login_data = await login(await request.body(), ip, db_conn)
  File "/osu-server/bancho.py/app/api/domains/cho.py", line 813, in login
    data += app.packets.friends_list(p.friends)
  File "/osu-server/bancho.py/app/packets.py", line 1070, in friends_list
    return write(ServerPackets.FRIENDS_LIST, (friends, osuTypes.i32_list))
  File "/osu-server/bancho.py/app/packets.py", line 723, in write
    ret += _noexpand_types[p_type](p_args)
  File "/osu-server/bancho.py/app/packets.py", line 587, in write_i32_list
    ret += i.to_bytes(4, "little")
OverflowError: can't convert negative int to unsigned
```

**Comment by infernalfire72** [comment]
> > the better question is why is it trying to serialize as unsigned when "i32" should be signed integer in the first place
> 
> after a little bit of googling I found this post: https://stackoverflow.com/questions/52022443/python-convert-a-negative-integer-into-bytesinged-true-but-convert-back-it-b
> 
> https://github.com/osuAkatsuki/bancho.py/blob/08d10f8283a73b06113134d38b41371832a7beef/app/packets.py#L587
> 
> I think change this line to following code could resolve the problem?
> 
> ```python
>  ret += i.to_bytes( 4, byteorder='little', signed=True )
> ```

yep, this fixes it

**Comment by cmyui** [comment]
never would have guessed the default would be unsigned tbh, but okay i'll remember to just use the keyword arg every time

fixed in [97be19c](https://github.com/osuAkatsuki/bancho.py/commit/97be19c87180c6fcd52adc96c114ef7d8347528c)

but you should probably look into why it's ending up with -1 as well, since that's not right

**Comment by arily** [comment]
> never would have guessed the default would be unsigned tbh, but okay i'll remember to just use the keyword arg every time
> 
> fixed in [97be19c](https://github.com/osuAkatsuki/bancho.py/commit/97be19c87180c6fcd52adc96c114ef7d8347528c)
> 
> but you should probably look into why it's ending up with -1 as well, since that's not right

I am taking a guess, those records may be added by gulag, since all of the affected users has relatively low id.

there are few more lines that seems need to change to me:
https://github.com/osuAkatsuki/bancho.py/blob/08d10f8283a73b06113134d38b41371832a7beef/app/packets.py#L650

https://github.com/osuAkatsuki/bancho.py/blob/08d10f8283a73b06113134d38b41371832a7beef/app/packets.py#L652

and two more int to_bytes just down below but I am not sure if those needs to be signed too.

**Comment by cmyui** [comment]
yeah will take a look at all the other calls later, i spotted a couple of spots
