### ISSUE TITLE
`!server` command requirements parsing fails

### ISSUE THREAD

**Issue by shoei1944** [osuAkatsuki/bancho.py#335]
```
Traceback (most recent call last):
  File "/home/shoei1944/server/app/commands.py", line 2567, in process_commands
    res = await cmd.callback(
  File "/home/shoei1944/server/app/commands.py", line 1367, in server
    requirements_info = "\n".join(
  File "/home/shoei1944/server/app/commands.py", line 1368, in <genexpr>
    " | ".join("{} v{}".format(*pkg.split("==")) for pkg in section)
  File "/home/shoei1944/server/app/commands.py", line 1368, in <genexpr>
    " | ".join("{} v{}".format(*pkg.split("==")) for pkg in section)
IndexError: Replacement index 1 out of range for positional args tuple
[04:44:28PM] <shoei1944 (3)> @ <#osu>: !server
```

![image](https://user-images.githubusercontent.com/119505551/211161418-36cfd003-32c6-45f7-8b43-c26399a956c6.png)

**Comment by cmyui** [comment]
Ahh wow that code is pretty based.. It depends on `requirements.txt` being in pwd as well as it using explicit versioning..

If we really want to keep `!server` showing dependency versions, it may be possible to pull them from the runtime, that would be much better than depending on this file

On a related note, eventually I would really like to remove this line from main.py; which exists because the server stores data in `bancho.py/.data`.
https://github.com/osuAkatsuki/bancho.py/blob/3a9efd82e8e611c50a58d7f3c2f4c0f48484b4df/main.py#L23
